### PR TITLE
Maybe fix iFastCopy

### PR DESCRIPTION
**Pull request by runer112**
See https://www.cemetech.net/forum/viewtopic.php?p=284515

Here's my build that someone with an affected calc should try to confirm that this actually fixes the issue (and probably one or two people with unaffected calcs should confirm that this doesn't create a new issue): [dcs7.zip](https://github.com/KermMartian/Doors_CS_7/files/4302273/dcs7.zip)

### CODE REVIEW

**Comment by runer112** [comment]
Seems to have fixed the issue for the first person who tried it: https://www.cemetech.net/forum/viewtopic.php?p=284526#284526

**Comment by runer112** [comment]
It's also probably worth doing a quick check that some common assembly programs/games known to use iFastCopy seem okay.

**Comment by runer112** [comment]
Two more testimonials that this patch fixes the issue, without report of any newly introduced issues:
1. https://www.cemetech.net/forum/viewtopic.php?p=285366&sid=9e5b910c153ecb25e7ef3881cd428852#285366
2. https://www.cemetech.net/forum/viewtopic.php?p=285394&sid=9e5b910c153ecb25e7ef3881cd428852#285394

**Comment by Jeffitus** [comment]
Okay, I found a new issue with this build; det([[42 returns 42 even though Basic libraries are enabled in options (which should make it return 1337). Haven't tried on actual hardware yet but Wabbit and jsTIfied both behave this way.

**Comment by runer112** [comment]
> Okay, I found a new issue with this build; det([[42 returns 42 even though Basic libraries are enabled in options (which should make it return 1337). Haven't tried on actual hardware yet but Wabbit and jsTIfied both behave this way.

I definitely didn't change any code related to this. It's possible that there's some configuration thing needed for this to work that I missed when building it myself. If not, this behavior is almost certainly not new.

**Comment by Jeffitus** [comment]
Yep, this problem occurs when just building it normally as well. Should I make a separate Issue for it?

**Comment by runer112** [comment]
> Yep, this problem occurs when just building it normally as well. Should I make a separate Issue for it?

Seems like a good idea.

**Comment by crispyJim** [comment]
> See https://www.cemetech.net/forum/viewtopic.php?p=284515
> 
> Here's my build that someone with an affected calc should try to confirm that this actually fixes the issue (and probably one or two people with unaffected calcs should confirm that this doesn't create a new issue): [dcs7.zip](https://github.com/KermMartian/Doors_CS_7/files/4302273/dcs7.zip)

hey runer112 im trying to play Phoenix on my ti84+ and i cant seem to get it to work without the screen being all glitched and distorted. I also ran the game from this doors cs7 file you linked, and it still was glitched. could you make a fixed version of phoenix?

**Comment by Eeems** [comment]
@crispyJim Have you run alcdfix? https://www.ticalc.org/archives/files/fileinfo/366/36608.html

**Comment by crispyJim** [comment]
> @crispyJim Have you run alcdfix? https://www.ticalc.org/archives/files/fileinfo/366/36608.html

Yes.

**Comment by CVSoft** [comment]
I've tested this on a real TI-83 Plus with the new LCD driver. Works without issue, aside from the det([[42]])=42 thing. 

Also functional is replacing all the `ld c,$10 \ ... \ in a,(c) \ rla \ jr c,addr` with `call lcd_busy_quick`, which I don't believe requires switching CPU speed (and makes the nspire versions of the existing routines redundant). Whatever's faster, I suppose. I haven't tested anything on a 15 MHz calculator. Anything that avoids reading the status port should work, as long as your timings allow enough delay for Toshiba display drivers to function properly as well.

I've also added/corrected some documentation about the new LCD drivers to WikiTI.

**Comment by KermMartian** [comment]
I did some fairly rigorous testing of this on an older TI-84 Plus Silver Edition today, freshly recompiled on my own machine from this branch:
* Running TI-BASIC and ASM (including Ion) programs worked
* Running archived programs worked
* Program icons are showed correctly, including BASIC program icons
* All the menus work, including the Display menu
* Various hooks like HomeRun and [ON][PRGM] work correctly
* Both the mouse and keyboard shortcuts work correctly.

I run into a strange Heisenbug that I was able to replicate three times and then not at all thereafter, which appeared to require these or some subset of these steps:
1. Launch and quit Doors CS
2. Create a TI-BASIC program with the following contents: `::DCSB \ :"FF818181818181FF \ Disp "HELLO WORLD`
3. Run this program via HomeRun, then open Doors CS, view the icon, and run the program
4. Quit and run @elfprince13 's modified Phoenix from HomeRun
5. Choose 3 (About), then [CLEAR].
6. Crash after PHOENIX closes but before the TI-OS regains control

This particular TI-84+SE has OS 2.40, so I'm willing to chalk it up to that.

**Comment by runer112** [comment]
@KermMartian Thanks for testing this out. Did you test `det[[42` in your build? One bug my build clearly had from numerous reports was that not working.

**Comment by CVSoft** [comment]
I have quite a few calculators with the new Kinpo LCD drivers at my disposal. For testing, I am using a TI-83 Plus L-0521F, OS 1.19; a TI-84 Plus L-0421AF, OS 2.55MP; a TI-Nspire with TI-84 Plus Keypad, OS 2.56MP; and a control sample TI-83 Plus S-0505F, OS 1.19. I am running @runer112's fastcopy bugfix branch, 8061c7015a0ac153f42fc0bf31aceeb1286d81f2, assembled in Brass 1.0.5.3. I haven't tested a whole lot so far, but I have not encountered any display inconsistencies so far. I have verified so far:
* Running TI-BASIC programs worked; ASM programs appear to work but I have only tested against a version of Phoenix I modified personally
* Running an archived program worked
* Program icons are showed correctly; have not tested BASIC program icons
* All the menus work, including the Display menu
* HomeRun and [ON][PRGM] hooks work correctly
* Consistent with #2, DCSB libraries are not available, and det([[42 returns 42. The control calculator (TI-83 Plus S-0505F, OS 1.19) shows this as well, which I do not find surprising. 

Where can I obtain @elfprince13's modified Phoenix to try and reproduce the Heisenbug?

**Comment by crispyJim** [comment]
i have no clue about any of what youre talking about plus the email ur replying to is super oldSent using the mobile mail appOn 7/30/22 at 6:37 PM, CVSoft wrote:
                
            
            
                
                    From: "CVSoft" ***@***.***>Date: July 30, 2022To: "KermMartian/Doors_CS_7" ***@***.***>Cc: "crispyJim" ***@***.***>,"Mention" ***@***.***>Subject: Re: [KermMartian/Doors_CS_7] Maybe fix iFastCopy (#1)
                
                
I have quite a few calculators with the new Kinpo LCD drivers at my disposal. For testing, I am using a TI-83 Plus L-0521F, OS 1.19; a TI-84 Plus L-0421AF, OS 2.55MP; a TI-Nspire with TI-84 Plus Keypad, OS 2.56MP; and a control sample TI-83 Plus S-0505F, OS 1.19. I am running @runer112's fastcopy bugfix branch, 8061c70, assembled in Brass 1.0.5.3. I haven't tested a whole lot so far, but I have not encountered any display inconsistencies so far. I have verified so far:

Running TI-BASIC programs worked; ASM programs appear to work but I have only tested against a version of Phoenix I modified personally
Running an archived program worked
Program icons are showed correctly; have not tested BASIC program icons
All the menus work, including the Display menu
HomeRun and [ON][PRGM] hooks work correctly
Consistent with #2, DCSB libraries are not available, and det([[42 returns 42. The control calculator (TI-83 Plus S-0505F, OS 1.19) shows this as well, which I do not find surprising.

Where can I obtain @elfprince13's modified Phoenix to try and reproduce the Heisenbug?

**Comment by KermMartian** [comment]
> Where can I obtain @elfprince13's modified Phoenix to try and reproduce the Heisenbug?

I believe it's this one: https://www.ticalc.org/archives/files/fileinfo/393/39359.html

**Comment by KermMartian** [comment]
As noted in #2, d48ba7a2789ecea5ccc8b8961511142e711cbba5 fixes the missing basic libraries, but that inexplicable regression makes me worry that there are other undetected regressions.

**Comment by crispyJim** [comment]
That one guy gave me modified phoenix and it works with ti 84 plus and i have it
Sent using the mobile mail app

**Comment by KermMartian** [comment]
A few programs that I tested or tried to test:
* The demo tilemapper that comes with xLIB works great.
* An [xLIB clone of BlockDude](https://www.ticalc.org/archives/files/fileinfo/411/41140.html) works well.
* xLIB xLIB Revolution does not work properly; it gets tripped up on `1:real(0):Ans` (but the documentation suggests that real(0) doesn't have any expected output in Ans, so I'm not worried about this).

**Comment by elfprince13** [comment]
True--
~Thomas

**Pull request merged**
